---
- name: Add repository
  become: yes
  yum_repository:
    state: present
    name: docker
    description: Docker repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: yes

- name: Install Docker
  become: yes
  package:
    name:
      - docker-engine
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: latest

- name: Add user vagrant to docker group
  become: yes
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Create docker configuration directory
  become: yes
  file:
    state: directory
    path: /etc/docker

- name: Copy daemon config
  become: yes
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
  register: daemon_config

- name: Start Docker service
  become: yes
  service:
    name: docker
    state: '{{ "restarted" if daemon_config is changed else "started" }}'
    enabled: yes
