admin:
  existingSecret: grafana-secret
  userKey: username
  passwordKey: password

plugins:
  - grafana-kubernetes-app

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.default.svc.cluster.local
      access: proxy
      isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      type: file
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus

    kubernetes:
      gnetId: 315
      revision: 3
      datasource: Prometheus

service:
  type: LoadBalancer

persistence:
  enabled: true
