---
- name: Generate private key
  openssl_privatekey:
    path: '{{ pki_path }}/{{ pki_cert_name }}.pem'
    passphrase: '{{ pki_cert_pass | default(omit) }}'
    cipher: '{{ pki_cert_cipher | default(omit) }}'

- name: Generate CSR
  openssl_csr:
    path: '{{ pki_path }}/{{ pki_cert_name }}.csr'
    privatekey_path: '{{ pki_path }}/{{ pki_cert_name }}.pem'
    privatekey_passphrase: '{{ pki_cert_pass | default(omit) }}'
    common_name: '{{ pki_cert_subject | default(pki_cert_name) }}'
    country_name: US
    organization_name: '{{ pki_cert_organization_name | default("Lab") }}'
    organizational_unit_name: Lab
    subject_alt_name: '{{ pki_cert_san | default(omit) }}'
    key_usage: '{{ pki_cert_key_usage | default(["digitalSignature", "keyEncipherment"]) }}'
    extended_key_usage: '{{ pki_cert_ext_key_usage | default(["serverAuth"]) }}'

- name: Generate certificate
  openssl_certificate:
    path: '{{ pki_path }}/{{ pki_cert_name }}.crt'
    csr_path: '{{ pki_path }}/{{ pki_cert_name }}.csr'
    ownca_path: '{{ pki_path }}/intermediate.crt'
    ownca_privatekey_path: '{{ pki_path }}/intermediate.pem'
    ownca_privatekey_passphrase: '{{ pki_intermediateca_pass }}'
    provider: ownca

- name: Generate PKCS12 package
  openssl_pkcs12:
    path: '{{ pki_path }}/{{ pki_cert_name }}.pfx'
    friendly_name: '{{ pki_cert_name }}'
    passphrase: '{{ pki_cert_pass | default(omit) }}'
    privatekey_path: '{{ pki_path }}/{{ pki_cert_name }}.pem'
    privatekey_passphrase: '{{ pki_cert_pass | default(omit) }}'
    certificate_path: '{{ pki_path }}/{{ pki_cert_name }}.crt'
    ca_certificates:
      - '{{ pki_path }}/root.crt'
      - '{{ pki_path }}/intermediate.crt'
