---
- set_fact:
    role_dir: '{{ role_path }}'

- import_tasks: kubectl_config.yaml
- import_tasks: rbac.yaml
- import_tasks: flannel.yaml
- import_tasks: metallb.yaml
- import_tasks: helm.yaml
- import_tasks: localstorage.yaml
- import_tasks: coredns.yaml
- import_tasks: ingress_nginx.yaml
- import_tasks: prometheus_grafana.yaml
- import_tasks: efk_stack.yaml
